"""Initial database schema

Revision ID: 1f67a7d81b62
Revises: 
Create Date: 2025-06-29 04:21:09.718164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f67a7d81b62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processing_eligible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_files')),
    sa.UniqueConstraint('checksum', name=op.f('uq_audio_files_checksum')),
    sa.UniqueConstraint('file_path', name=op.f('uq_audio_files_file_path'))
    )
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_files_id'), ['id'], unique=False)

    op.create_table('audio_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('rms_level', sa.Float(), nullable=True),
    sa.Column('peak_level', sa.Float(), nullable=True),
    sa.Column('dynamic_range', sa.Float(), nullable=True),
    sa.Column('spectral_centroid', sa.Float(), nullable=True),
    sa.Column('spectral_rolloff', sa.Float(), nullable=True),
    sa.Column('zero_crossing_rate', sa.Float(), nullable=True),
    sa.Column('lufs_integrated', sa.Float(), nullable=True),
    sa.Column('lufs_short_term', sa.Float(), nullable=True),
    sa.Column('lufs_momentary', sa.Float(), nullable=True),
    sa.Column('true_peak', sa.Float(), nullable=True),
    sa.Column('mfcc_features', sa.JSON(), nullable=True),
    sa.Column('spectral_features', sa.JSON(), nullable=True),
    sa.Column('tempo_features', sa.JSON(), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('analysis_duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_metadata'))
    )
    with op.batch_alter_table('audio_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_metadata_audio_file_id'), ['audio_file_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audio_metadata_id'), ['id'], unique=False)

    op.create_table('job_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('VALIDATION', 'FEATURE_EXTRACTION', 'AI_ANALYSIS', 'PARAMETER_PREDICTION', 'AUDIO_PROCESSING', 'QUALITY_CHECK', 'FINALIZATION', name='processingstage'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('stage_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_duration', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_progress'))
    )
    with op.batch_alter_table('job_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_progress_job_id'), ['job_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('input_file_id', sa.UUID(), nullable=False),
    sa.Column('reference_file_id', sa.UUID(), nullable=True),
    sa.Column('output_file_path', sa.String(length=500), nullable=True),
    sa.Column('processing_mode', sa.Enum('AUTO', 'REFERENCE', 'HYBRID', name='processingmode'), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_stage', sa.Enum('VALIDATION', 'FEATURE_EXTRACTION', 'AI_ANALYSIS', 'PARAMETER_PREDICTION', 'AUDIO_PROCESSING', 'QUALITY_CHECK', 'FINALIZATION', name='processingstage'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('processing_duration', sa.Float(), nullable=True),
    sa.Column('cpu_time', sa.Float(), nullable=True),
    sa.Column('memory_peak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_input_file_id'), ['input_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_reference_file_id'), ['reference_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_reference_file_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_input_file_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('job_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_progress_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_progress_id'))

    op.drop_table('job_progress')
    with op.batch_alter_table('audio_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_audio_metadata_audio_file_id'))

    op.drop_table('audio_metadata')
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_files_id'))

    op.drop_table('audio_files')
    # ### end Alembic commands ###
